# Ruff Configuration
# Documentation: https://docs.astral.sh/ruff/

[tool.ruff]
exclude = [
    ".direnv",
    ".git",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "env.py",
    "manage.py",
    "media",
    "migrations",
    "node_modules",
    "site-packages",
    "static",
    "templates",
    "venv",
    "__pycache__",
    "wsgi.py",
    "asgi.py",
]
line-length = 79
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "Q000",
    "Q001",
    "Q003",
    "E203",
    "DJ001",
]
select = [
    "E",
    "F",
    "B",
    "C90",
    "DJ",
    "I",
    "N",
    "UP",
    "RUF",
    "S",
    "PL",
    "PIE",
    "W",
    "ICN",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"settings.py" = [
    "F401",
    "F403",
    "F405",
    "E501",
]
"tests.py" = [
    "F401",
    "S101",
]

[tool.ruff.format]
quote-style = "single"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
